name: Florence
description: model for detection lung deceases

_target_: innofw.core.models.torch.architectures.detection.Florence
tokenizer_save_path: "innofw/core/integrations/florence/tokenizer/"
device: "cpu"
task_prompt: "<CAPTION_TO_PHRASE_GROUNDING>"
text_input: "cardiomegaly"
