_target_: innofw.core.datamodules.lightning_datamodules.HDF5LightningDataModule  # todo:
train:
  source: /mnt/nvmestorage/qb/data_n_weights/landslides-bin-seg-s2/210223/processed/train

test:
  source: /mnt/nvmestorage/qb/data_n_weights/landslides-bin-seg-s2/210223/processed/test/

num_workers: 32
batch_size: 16
channels_num: 4
w_sampler: True

name: something
task: image-segmentation
description: some
markup_info: some
date_time: some