task:
  - tabular-clustering

name: credit_cards
description: "
The dataset contains transactions made by credit cards in September 2013 by European cardholders.
This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions.
The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.
 
Citations:
- Andrea Dal Pozzolo, Olivier Caelen, Reid A. Johnson and Gianluca Bontempi. 
Calibrating Probability with Undersampling for Unbalanced Classification. 
In Symposium on Computational Intelligence and Data Mining (CIDM), IEEE, 2015
- Dal Pozzolo, Andrea; Caelen, Olivier; Le Borgne, Yann-Ael; Waterschoot, Serge; Bontempi, Gianluca.
Learned lessons in credit card fraud detection from a practitioner perspective,
Expert systems with applications,41,10,4915-4928,2014, Pergamon
- Dal Pozzolo, Andrea; Boracchi, Giacomo; Caelen, Olivier; Alippi, Cesare; Bontempi, Gianluca. 
Credit card fraud detection: a realistic modeling and a novel learning strategy, IEEE transactions on neural networks 
and learning systems,29,8,3784-3797,2018,IEEE
- Dal Pozzolo, Andrea Adaptive Machine learning for credit card fraud detection ULB MLG PhD thesis
 (supervised by G. Bontempi)
- Carcillo, Fabrizio; Dal Pozzolo, Andrea; Le Borgne, Yann-Aël; Caelen, Olivier; Mazzer, Yannis; Bontempi, Gianluca. 
Scarff: a scalable framework for streaming credit card fraud detection with Spark, 
Information fusion,41, 182-194,2018,Elsevier
- Carcillo, Fabrizio; Le Borgne, Yann-Aël; Caelen, Olivier; Bontempi, Gianluca. 
Streaming active learning strategies for real-life credit card fraud detection: assessment and visualization,
 International Journal of Data Science and Analytics, 5,4,285-300,2018,Springer International Publishing
- Bertrand Lebichot, Yann-Aël Le Borgne, Liyun He, Frederic Oblé, Gianluca Bontempi Deep-Learning Domain Adaptation
Techniques for Credit Cards Fraud Detection, INNSBDDL 2019: Recent Advances in Big Data and Deep Learning,
pp 78-88, 2019
- Fabrizio Carcillo, Yann-Aël Le Borgne, Olivier Caelen, Frederic Oblé, 
Gianluca Bontempi Combining Unsupervised and Supervised Learning in Credit Card Fraud Detection Information Sciences,2019
- Yann-Aël Le Borgne, Gianluca Bontempi Reproducible machine Learning for Credit Card Fraud Detection - Practical Handbook
- Bertrand Lebichot, Gianmarco Paldino, Wissam Siblini, Liyun He, Frederic Oblé,
 Gianluca Bontempi Incremental learning strategies for credit cards fraud detection, 
 IInternational Journal of Data Science and Analytics"

markup_info: The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.
date_time: 28.07.2022

target_col: TENURE

_target_: innofw.core.datamodules.pandas_datamodules.PandasDataModule

train:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/credit_cards/train.zip
  target: ./data/credit-cards/train

test:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/credit_cards/test.zip
  target: ./data/credit-cards/test

infer:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/credit_cards/train.zip
  target: ./data/credit-cards/infer
