task:
  - semantic_segmentation

name: stroke_segmentation
description: "Created by AT&T Laboratories Cambridge.
Link: https://cam-orl.co.uk/facedatabase.html"

markup_info: Набор данных содержит черно белые изображения мозга
date_time: 19.07.2022

_target_: innofw.core.datamodules.lightning_datamodules.semantic_segmentation.stroke_dm.StrokeSegmentationDatamodule

train:
  source: /home/user/data/train

test:
  source: /home/user/data/test

infer:
  source: /home/user/data/infer


num_workers: 0

val_size: 0.2
