repos:
-   repo: local
    hooks:
    - id: update-requirements-txt
      name: update-requirements-txt
      description: 'Generate requirements.txt based on poetry.lock'
      entry: poetry
      args: [export, --without-hashes, --format, requirements.txt, --output, requirements.txt]
      language: system
      pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args:
        - --line-length=79
        - --target-version=py38
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    -   id: autoflake
        args:
        - --in-place
        - --remove-all-unused-imports
        - --remove-duplicate-keys
        - --ignore-init-module-imports
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args:
            - --py38-plus
