grid_distortion:
  _target_: albumentations.GridDistortion
  always_apply: False
  p: 0.7
  num_steps: 5
  distort_limit:
      - -0.35
      - 0.35
  interpolation: 0
  border_mode: 0
  value:
      - 0
      - 0
      - 0
  mask_value: