_target_: innofw.core.datamodules.lightning_datamodules.HDF5LightningDataModule
train:
  source: /mnt/nvmestorage/qb/data_n_weights/water_erosion/220223/processed/train/

test:
  source: /mnt/nvmestorage/qb/data_n_weights/water_erosion/220223/processed/test/

num_workers: 32
batch_size: 16
channels_num: 4


name: something
task: image-segmentation
description: some
markup_info: some
date_time: some