name: Multiclass Segmentation
description: Calculates f1 score, Jaccard index and precision
task:
  - multiclass-image-segmentation


implementations:
  torch:
    F1_score:
      _target_: torchmetrics.F1Score
      num_classes: ${n_classes}
      task: multiclass
    Precision:
      _target_: torchmetrics.Precision
      num_classes: ${n_classes}
      task: multiclass
