task:
  - text-classification

name: noname
description: "Набор данных для классификации патологии легких по тексту"

markup_info: Набор данных содержит описание легких
date_time: 13.09.2023

_target_: innofw.core.datamodules.pandas_datamodules.lung_description_decision_datamodule.LungDescriptionDecisionPandasDataModule
target_col: "decision"

train:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/rtk/labels.zip
  target: ./data/lung_description/train
test:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/rtk/labels.zip
  target: ./data/lung_description/test
infer:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/rtk/labels.zip
  target: ./data/lung_description/infer

