defaults:
    - /augmentations/preprocessing:
      - sentinel2
    - /augmentations/combined:
        - none
    - /augmentations/position:
    - /augmentations/color:
    - /augmentations/postprocessing:
