defaults:
  - combined:
      - none
  - position:
      # - random_resized_crop
    #   - padding
      # - flip
      # - rotate90
      # - transpose
      # - grid_distortion
  - color:
      # - random_gamma
      # - blur
      # - random_brightness_contrast
  - postprocessing:
      - none
