name: chem-vae
description: vae for seq2seq modeling

_target_: innofw.core.models.torch.architectures.autoencoders.vae.VAE
encoder:
  _target_: innofw.core.models.torch.architectures.autoencoders.vae.Encoder
  in_dim: 609  # len(alphabet) * max(len_mols)
  hidden_dim: 128
  enc_out_dim: 128
decoder:
  _target_: innofw.core.models.torch.architectures.autoencoders.vae.GRUDecoder
  latent_dimension: 128
  gru_stack_size: 3
  gru_neurons_num: 128
  out_dimension: 29  # len(alphabet)
