# wandb sweep config
program: train.py
method: grid
metric:
  name: val_BinaryJaccardIndex
  goal: maximize

name: round7-try-tile-1600-w-weighted-pix-file_sampler_n_filtered
project: arable-bound-bin-seg-ndvi

parameters:
  experiments:
    values: [
      "semantic-segmentation/arable-bin-seg-ndvi/boundaries/tile1600-filtered-weighted-strong-aug_file_pix_weights",
    ]
  batch_size:
    value: 4

  models._target_:
    values: [
      "segmentation_models_pytorch.Unet",
    ]

  losses:
    values: [
             'semantic-segmentation/dice.yaml',
             'semantic-segmentation/jaccard.yaml',
             ]
  optimizers.lr:
    values: [
      3e-3,
      3e-4,
    ]

  epochs:
    values: [100]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
