# wandb sweep config
program: train.py
method: grid
metric:
  name: val_BinaryJaccardIndex
  goal: maximize

name: round3-try-diff-Unet-encoders
project: arable-bound-bin-seg-ndvi

parameters:
  experiments:
    value: "semantic-segmentation/arable-bin-seg-ndvi/boundaries/baseline-1024.yaml"

  batch_size:
    value: 16

  models._target_:
    values: [
      "segmentation_models_pytorch.Unet",
    ]

  models.encoder_name:
    values: [
      # "resnet34",
      "resnet101",
      # "resnet152",
      "dpn98",
      # "dpn107",
      # "mit_b1",
      # "mit_b3",
      # "mit_b5",
    ]

  losses:
    values: [
             'semantic-segmentation/focal_tversky_loss.yaml',
             'semantic-segmentation/dice_w_smooth.yaml',
            #  'semantic-segmentation/dice_w_smooth_0_2.yaml',
            #  'semantic-segmentation/dice_w_smooth_0_0_5.yaml',
             'semantic-segmentation/dice.yaml',
             'semantic-segmentation/jaccard.yaml',
            #  'semantic-segmentation/soft_bce_with_logits.yaml',
             ]
  optimizers:
    values: [
      'adam.yaml',
      # 'adam_w_weight_decay_0_0001.yaml',
    ]

  optimizers.lr:
    values: [
      3e-3,
      3e-4,
      # 3e-5,
    ]

  epochs:
    values: [50]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
