task:
  - НАЗВАНИЕ РЕШАЕМОЙ ЗАДАЧИ

name: ИМЯ ДАТАСЕТА
description: ОПИСАНИЕ
markup_info: ИНФОРМАЦИЯ ПО РАЗМЕТКЕ
date_time: ДАТА В ФОРМАТЕ 22.11.2222

_target_: ПУТЬ ДО КЛАССА ОТВЕЧАЮЩЕГО ЗА РАБОТУ С ДАТАСЕТОМ

train:
  source: URL / ЛОКАЛЬНЫЙ ПУТЬ
  target: ЛОКАЛЬНЫЙ ПУТЬ

test:
  source: URL / ЛОКАЛЬНЫЙ ПУТЬ
  target: ЛОКАЛЬНЫЙ ПУТЬ

infer:
  source: URL / ЛОКАЛЬНЫЙ ПУТЬ
  target: ЛОКАЛЬНЫЙ ПУТЬ

num_workers: КОЛВО ПОТОКОВ, ПРИМЕР - 2

val_size: ФРАКЦИЯ ОТ ТРЕНИРОВОЧНОЙ ВЫБОРКИ ДЛЯ ВАЛИДАЦИИ, ПРИМЕР - 0.2
channels_num: КОЛВО КАНАЛОВ В ИЗОБРАЖЕНИИ, ПРИМЕР - 3
image_size: РАЗМЕР ИЗОБРАЖЕНИЙ К ПОДАЧЕ В МОДЕЛЬ, ПРИМЕР - 800
num_classes: КОЛВО КЛАССОВ В ДАТАСЕТЕ, ПРИМЕР - 1
names:
  - НАЗВАНИЕ КЛАССА 1