task: 
  - text-ner

name: Drugprot
description: "Frigprot, 
Citation: Krallinger, Martin, Rabal, Obdulia, Miranda-Escalada, Antonio, & Valencia, Alfonso. (2021). 
DrugProt corpus: Biocreative VII Track 1 - Text mining drug and chemical-protein interactions (1.2) [Data set]. Zenodo. 
https://doi.org/10.5281/zenodo.5119892"
date_time: 26.07.2022
markup_info: "more information here: https://zenodo.org/record/5119892#.YyxRl9LP05l"

_target_: innofw.core.datamodules.lightning_datamodules.drugprot.DrugprotDataModule
train:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/drugprot/train.zip
  target: ./data/drugprot/train/
test:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/drugprot/test.zip
  target: ./data/drugprot/test/
infer:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/drugprot/test.zip
  target: ./data/drugprot/infer/

val_size: 0.2
tokenizer:
  _target_: transformers.BertTokenizerFast.from_pretrained
  pretrained_model_name_or_path: dmis-lab/biobert-base-cased-v1.2
entity_labelmapper:
  _target_: innofw.core.datamodules.lightning_datamodules.drugprot.LabelMapper
  label_dict: 
    NA: 0 
    PRESENT: 1
