defaults:
  - _self_
  - datasets:
  - models:
  - trainer: auto
  - metrics: auto
  - losses: auto
  - optimizers: auto
  - schedulers: auto
  - augmentations_train: none
  - augmentations_test: none
  - augmentations_val: none
  - loggings: auto
  - callbacks: auto
  - initializations:
  - wandb: default
  - clear_ml: disabled
  - experiments: ???
  - override hydra/job_logging: custom

project: ???
batch_size:
weights_path:
weights_freq:
ckpt_path:
stop_param:
experiment_name:
accelerator: cpu
#devices: 1
#gpus: 1
