defaults:
  - _self_
  - datasets:
  - models:
  - trainer: auto
  - metrics: auto
  - losses: auto
  - optimizers: auto
  - schedulers: auto
  - augmentations_train: none
  - augmentations_test: none
  - augmentations_val: none
  - loggings: auto
  - callbacks: auto
  - initializations:
  - clear_ml: disabled
  - experiments: ???

#experiment_name: ???
project: ???
task: ???
random_seed:
epochs:
batch_size:
weights_path:
weights_freq:
ckpt_path:
stop_param:

accelerator: gpu
#devices: 1
gpus: 1

# original_work_dir: ${hydra:runtime.cwd}
