task:
  - qsar-regression

name: toxicity_rabbit_skin_ld50
description: The dataset provides information on the lethal dose (LD50) values for various chemical substances applied to rabbit skin, indicating the dose required to cause death in 50% of the rabbit population under experimental conditions.

markup_info: Информация о разметке
date_time: 22.10.2024

_target_: innofw.core.datamodules.pandas_datamodules.QsarDataModule

train:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/toxisity_rabbit_skin_ld50/train.zip
  target: ./data/toxicity_rabbit_skin_ld50/train
test:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/toxisity_rabbit_skin_ld50/test.zip
  target: ./data/toxicity_rabbit_skin_ld50/test
infer:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/toxisity_rabbit_skin_ld50/test.zip
  target: ./data/toxicity_rabbit_skin_ld50/test
smiles_col: smiles
target_col: Toxicity Value
val_size: 0.2
