task:
  - image-detection

name: detection_lungs
description: Набор данных содержит РГ снимки легких

markup_info: Набор данных содержит разметку bounding box легких и патологий.
date_time: 18.07.2022

_target_: innofw.core.integrations.ultralytics.datamodule.UltralyticsDataModuleAdapter

train:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/lungs_detection/train.zip
  target: ./data/lungs/train/

test:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/lungs_detection/test.zip
  target: ./data/lungs/test/

infer:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/lungs_detection/infer.zip
  target: ./data/lungs/infer/


num_workers: 8

val_size: 0.2
channels_num: 3
image_size: 416
num_classes: 7
names:
  - 'Контуры сердца'
  - 'Правое лёгкое'
  - 'Левое лёгкое'
  - 'Купола диафрагмы'
  - 'Инфильтрация'
  - 'Иная патология'
  - 'Артефакт, сторонняя тень или надпись'
