task:
  - image-detection

#_target_: innofw.core.datamodules.lightning_datamodules.florence.FlorenceImageDataModuleAdapter
_target_: innofw.core.datamodules.lightning_datamodules.florence.FlorenceJSONLDataModuleAdapter # for jsonl data

name: florence
description: Набор данных
markup_info: Набор данных содержит разметку bounding box легких и патологий.
date_time: 17.11.2024
num_workers: 8
size_to: 768

train:
  target: ./data/florence/train/

test:
  target: ./data/florence/test/

infer:
  source: "https://api.blackhole.ai.innopolis.university/public-datasets/florence/infer.zip"
  target: "./data/florence/infer"

