task:
  - image-detection

name: florence
description: Набор данных
markup_info: Набор данных содержит разметку bounding box легких и патологий.
date_time: 17.11.2024

_target_: innofw.core.datamodules.lightning_datamodules.florence.FlorenceDataModuleAdapter

train:
  target: ./data/florence/train/

test:
  target: ./data/florence/test/

infer:
  source: "https://api.blackhole.ai.innopolis.university/public-datasets/florence/infer.zip"
  target: "./data/florence/infer"

num_workers: 8
image_to: 768
