task:
  - all

implementations:
  torch:
    Custom:
      function:
        _target_: torch.optim.lr_scheduler.LambdaLR
        lr_lambda:
          _target_: innofw.schedulers.old_pipeline.lr_cyclic
          decay: 0.01
          decay_step: 1.2
          cyclic_decay: 0.9
          cyclic_len: 50
        last_epoch: -1
