name: Segmentation
description: Average of Jaccard and BinaryFocal losses
task:
  - image-segmentation

implementations:
  torch:
    JaccardLoss:
      weight: 1.0
      object:
        _target_: pytorch_toolbelt.losses.JaccardLoss
        mode: binary
        from_logits: True
