name: Segmentation
description: Dice Loss
task:
  - image-segmentation

implementations:
  torch:
    DiceLoss:
      weight: 1.0
      object:
        _target_: pytorch_toolbelt.losses.DiceLoss
        mode: binary
        from_logits: True
        smooth: 0.1
        eps: 1e-7

        # classes: None
        # log_loss: False