name: Segmentation
description: Average of Jaccard and BinaryFocal losses
task:
  - image-segmentation

implementations:
  torch:
    FocalTverskyLoss:
      weight: 1
      object:
        _target_: innofw.core.losses.focal_tversky_loss.FocalTverskyLoss
        alpha: 0.5
        beta: 0.5
        gamma: 1
        # weight: 1