name: Segmentation
description: SoftBCEWithLogitsLoss
task:
  - image-segmentation

implementations:
  torch:
    SoftBCEWithLogitsLoss:
      weight: 1
      object:
        _target_: pytorch_toolbelt.losses.SoftBCEWithLogitsLoss
        # weight:
          # _target_: torch.Tensor
          # - 0.7
          # - 1.3
# args: [[0.7, 1.3]]
# smooth_factor: 0.05
# pos_weight: 
#   _target_: torch.Tensor
#   args: [[1.5]]  # increase the impact of the foreground class