task:
  - image-segmentation

implementations:
  torch:
    Compose:
      object:
        _target_: albumentations.Compose
        transforms:
          # - _target_: albumentations.ShiftScaleRotate
          #   # scale_limit: (-0.5, 1.0)
          #   shift_limit: 0
          #   rotate_limit: 180
          - _target_: albumentations.Flip
          # - _target_: albumentations.Transpose
          #   p: 0.5
          #   always_apply: False
          # - _target_: albumentations.Flip
          # - _target_: albumentations.RandomRotate90
          # - _target_: albumentations.ElasticTransform
          #   p: 0.3
          # - _target_: albumentations.OneOf
          #   p: 0.7
          #   transforms:
          #     - _target_: albumentations.RandomGamma
          #       p: 1.0
          #       gamma_limit:
          #         - 80
          #         - 120
          #       eps: 1e-7
          #     - _target_: albumentations.RandomBrightnessContrast
          #       brightness_limit:
          #         - -0.03
          #         - 0.05
          #       contrast_limit: 0.5
