_target_: segmentation_models_pytorch.FPN
description: Base Unet segmentation model with 1 channel input
name: FPN
in_channels: 1
classes: 4
encoder_name: 'efficientnet-b7'
encoder_weights:
activation:
