_target_: segmentation_models_pytorch.Unet 
description: Base Unet segmentation model with 3 channels input
name: Unet
in_channels: 3
classes: 1
encoder_name: resnet34
encoder_weights:
#activation: sigmoid