defaults:
    - /augmentations/preprocessing:
    - /augmentations/combined:
        - none
    - /augmentations/position:
        - random_resized_crop
        - flip
        - rotate90
        - transpose
        - grid_distortion
    - /augmentations/color:
        - random_gamma
        - blur
    - /augmentations/postprocessing:
