defaults:
    - /augmentations/preprocessing:
        - to_pil_image
        - resize
    - /augmentations/combined:
        - none
    - /augmentations/position:
      - random_horizontal_flip
    - /augmentations/color:
    - /augmentations/postprocessing:
      - to_tensor_copy
      - normalize
# task:
#   - one-shot-learning
