name: Docker clean

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker images
    - name: Check disk space
      run: df . -h
    - name: Free disk space
      run: |
          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
          sudo rm -rf \
            /opt/ghc \
            /usr/local/.ghcup \
            /usr/lib/jvm || true
    - name: Check disk space
      run: df . -h
